import { test, expect } from '@playwright/test';
import { Store } from '../../src/store.js';
import { join } from 'node:path';
let ownerKey:string;
test.beforeAll(()=>{
  const store=new Store(join(process.env.DISC_E2E_DIR!,'demo'));
  ownerKey=store.issueKey('Alex · server owner',true,null).key;store.close();
});
test('owner signs in, moderates, creates a staff key, and staff resets through the dashboard',async({page})=>{
  const errors:string[]=[];
  page.on('pageerror',e=>errors.push(e.message));
  page.on('console',msg=>{if(msg.type()==='error'&&!msg.text().includes('401'))errors.push(msg.text());});
  await page.goto('/');
  await page.getByLabel('Dashboard access key').fill(ownerKey);
  await page.getByRole('button',{name:'Enter dashboard'}).click();
  await expect(page.getByRole('heading',{name:'Your community, at a glance.'})).toBeVisible();
  await expect(page.locator('#nav-count')).toHaveText('10');
  await page.screenshot({path:'.data/dashboard-desktop.png',fullPage:true});
  await page.getByRole('button',{name:'Members',exact:false}).first().click();
  await page.getByLabel('Search members').fill('Sophie');
  await expect(page.locator('#member-table tbody tr')).toHaveCount(1);
  await page.getByRole('button',{name:'Manage',exact:true}).click();
  await page.getByLabel('Reason',{exact:true}).fill('Please keep the conversation on topic.');
  await page.getByRole('button',{name:'Apply action'}).click();
  await expect(page.getByRole('dialog')).not.toBeVisible();
  await page.getByRole('button',{name:'Warning history for Sophie'}).click();
  await expect(page.getByRole('dialog')).toContainText('Please keep the conversation on topic.');
  await page.getByRole('button',{name:'Close dialog'}).click();
  await page.getByRole('button',{name:'Access keys',exact:true}).click();
  await page.getByRole('button',{name:'Generate key',exact:true}).click();
  await page.getByLabel('Key label').fill('Sophie <img src=x onerror=alert(1)>');
  await page.getByRole('button',{name:'Generate access key'}).click();
  await expect(page.locator('#generated-key')).toBeVisible();
  const staffKey=(await page.locator('#generated-key').textContent())!;
  await page.getByRole('button',{name:'Done',exact:true}).click();
  await expect(page.locator('.keys-table')).toContainText('Sophie <img src=x onerror=alert(1)>');
  await expect(page.locator('.keys-table img')).toHaveCount(0);
  await page.getByRole('button',{name:'Sign out',exact:true}).click();
  await page.getByLabel('Dashboard access key').fill(staffKey);
  await page.getByRole('button',{name:'Enter dashboard'}).click();
  await expect(page.getByRole('heading',{name:'Your community, at a glance.'})).toBeVisible();
  await expect(page.locator('#keys-nav')).toBeHidden();
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
  await page.screenshot({path:'.data/dashboard-mobile.png',fullPage:true});
  await page.getByRole('button',{name:'Toggle navigation'}).click();
  await page.getByRole('button',{name:'Reset server',exact:true}).click();
  await expect(page.locator('#reset-preview')).toBeVisible();
  await page.getByRole('button',{name:'Preview reset'}).click();
  await expect(page.getByText('Review your reset', {exact:true})).toBeVisible();
  await expect(page.locator('.preview-targets').first()).toContainText('Sophie');
  await page.getByLabel('Type the server name exactly').fill('The Midnight Collective');
  await page.getByLabel('Type RESET SERVER to confirm').fill('RESET SERVER');
  await page.getByRole('button',{name:'Run demo reset'}).click();
  await expect(page.getByText('Reset results',{exact:true})).toBeVisible();
  await expect(page.getByText('17 completed',{exact:true})).toBeVisible();
  await expect(page.getByText('0 failed',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Back to reset setup'}).click();
  await expect(page.locator('#nav-count')).toHaveText('2');
  await expect(page.locator('#reset-preview')).toBeVisible();
  expect(errors).toEqual([]);
});
